[package]
name = "inari"
version = "0.2.1"
authors = ["Masashi Mizuno <mizuno@gsinet.co.jp>"]
edition = "2018"
description = "A Rust implementation of set-based interval arithmetic."
documentation = "https://docs.rs/inari"
readme = "README.md"
repository = "https://github.com/mizuno-gsinet/inari"
license = "MIT"
keywords = ["arithmetic", "interval", "math", "numerics"]
categories = ["mathematics", "science"]
include = [
  "/examples/**",
  "/src/**",
  "/tests/**",
  "/Cargo.toml",
  "/CHANGELOG.md",
  "/LICENSE",
  "/README.md",
]

[package.metadata.docs.rs]
all-features = true

[profile.release]
lto = true

[features]
default = ["gmp"]
gmp = ["gmp-mpfr-sys", "nom", "rug"]
tau_constant = []
_reserve_u64_in_dec_interval = []

[dependencies]
gmp-mpfr-sys = { version = "1.2", default-features = false, features = ["mpfr"], optional = true }
hexf = "0.1.0"
nom = { version = "5", optional = true }
rug = { version = "1.9", default-features = false, features = ["float", "integer", "rational"], optional = true }
static_assertions = "1.1"

[[example]]
name = "cancellation"
required-features = ["gmp"]

[[example]]
name = "exact"
required-features = ["gmp"]

[[example]]
name = "parse"
required-features = ["gmp"]

[[example]]
name = "quadratic"
required-features = ["gmp"]
