[package]
name = "inari"
version = "0.7.0"
authors = ["Masashi Mizuno <mizuno@gsinet.co.jp>"]
edition = "2018"
description = "A Rust implementation of set-based interval arithmetic."
documentation = "https://docs.rs/inari"
readme = "README.md"
repository = "https://github.com/mizuno-gsinet/inari"
license = "MIT"
keywords = ["arithmetic", "interval", "math", "numerics"]
categories = ["mathematics", "science"]
include = [
  "/examples/**",
  "/src/**",
  "/tests/**",
  "/Cargo.toml",
  "/CHANGELOG.md",
  "/doc-header.html",
  "/LICENSE",
  "/README.md",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--extend-css",
  "src/_docs/extra.css",
  "--html-in-header",
  "src/_docs/header.html",
]

[profile.release]
lto = true

[features]
default = ["gmp"]
avx512 = []
gmp = ["gmp-mpfr-sys", "nom", "rug"]

[dependencies]
static_assertions = "1.1"

[dependencies.gmp-mpfr-sys]
version = "1.4"
default-features = false
features = ["mpfr"]
optional = true

[dependencies.nom]
version = "6.0"
default-features = false
features = ["std"]
optional = true

[dependencies.rug]
version = "1.11"
default-features = false
features = ["float", "integer", "rational"]
optional = true

[[example]]
name = "cancellation"
required-features = ["gmp"]

[[example]]
name = "exact"
required-features = ["gmp"]

[[example]]
name = "parse"
required-features = ["gmp"]

[[example]]
name = "quadratic"
required-features = ["gmp"]
