name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          profile: minimal

      - name: Run tests (--no-default-features --features "avx512")
        run: RUSTFLAGS="-C target-feature=+avx512f" cargo test --release --no-default-features --features "avx512"

      - name: Run tests
        run: cargo test --release

      - name: Run tests (--no-default-features)
        run: cargo test --release --no-default-features

      - name: Clippy
        run: |
          cargo clippy --all-targets -- -Dwarnings
          cargo clippy --all-targets --features "avx512" -- -Dwarnings

      - name: Check format
        run: cargo fmt -- --check

      - name: Coverage
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
        run: |
          cargo clean
          cargo test

      - name: Gather coverage data
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
